### ISSUE TITLE
r

### ISSUE THREAD

**Issue by Deveroonie** [WebDevSimplified/Realtime-Simple-Chat-App#3]
r

**Comment by armando3069** [comment]
WTF bad code

**Comment by AirplanegoBrr** [comment]
Errors in console? Whats the problem? Is this a clone of #4 ??

**Comment by AirplanegoBrr** [comment]
Ok I fixed it turns out it **doesn't** work! (just by its self that is) I made a pull request so you can use that to get it to work 
You can find the pull request [Here](https://github.com/WebDevSimplified/Realtime-Simple-Chat-App/pull/6) you can download it [Here](https://github.com/AirplanegoBrr/Realtime-Simple-Chat-App/tree/main) Hope this helps! (I know this is a **very** old issue but meh)

**Comment by Deveroonie** [comment]
r

**Comment by AirplanegoBrr** [comment]
> No errors in console, #4 is a clone of this
#4 isn't a clone, use my pull request to fix

**Comment by 1plus1is6** [comment]
You need a web server for it to work, that is why it isn't working

**Comment by Deveroonie** [comment]
r
